# Generated by Django 5.1.3 on 2024-12-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plaintext_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
