# Generated by Django 5.1.3 on 2024-12-25 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_plaintext_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='plaintext_password',
        ),
    ]
