# Generated by Django 5.1.3 on 2024-12-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCompliance',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_data', models.JSONField()),
                ('job_status', models.CharField(choices=[('sales', 'Sales'), ('supervisor', 'Supervisor'), ('technician', 'Technician')], default='sales', max_length=20)),
                ('job_data', models.JSONField()),
            ],
        ),
    ]
