# Generated by Django 5.1.3 on 2024-12-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcompliance',
            name='isCompiled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testcompliance',
            name='job_status',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('technician', 'Technician')], default='supervisor', max_length=20),
        ),
    ]
