# Generated by Django 5.1.3 on 2024-12-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_testcompliance_iscompiled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcompliance',
            name='checklist_data',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testcompliance',
            name='job_status',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('technician', 'Technician'), ('complete', 'Complete')], default='supervisor', max_length=20),
        ),
    ]
