# Generated by Django 5.1.3 on 2024-12-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0006_alter_testcompliance_checklist_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcompliance',
            name='job_status',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('technician', 'Technician'), ('pending approval', 'Pending Approval'), ('Approved', 'Approved')], default='supervisor', max_length=20),
        ),
    ]
