# Generated by Django 5.1.3 on 2025-01-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0007_alter_testcompliance_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcompliance',
            name='compiled_report',
            field=models.FileField(blank=True, null=True, upload_to='test_reports/'),
        ),
        migrations.AlterField(
            model_name='testcompliance',
            name='checklist_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
