# Generated by Django 5.1.3 on 2025-01-04 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0008_testcompliance_compiled_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcompliance',
            name='checklist_data',
        ),
    ]
