# Generated by Django 5.1.3 on 2024-12-19 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation Date')),
                ('reporting_time', models.TimeField(verbose_name='Reporting Time')),
                ('checkout_time', models.TimeField(blank=True, null=True, verbose_name='Checkout Time')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Overtime Hours')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-creation_date'],
                'indexes': [models.Index(fields=['user'], name='attendancel_user_id_09ed86_idx'), models.Index(fields=['creation_date'], name='attendancel_creatio_05a6d6_idx')],
            },
        ),
    ]
