# Generated by Django 5.1.3 on 2024-12-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendancelisting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='working_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Working Hours'),
        ),
    ]
