# Generated by Django 5.1.3 on 2024-12-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendancelisting', '0002_attendance_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
