# Generated by Django 5.1.3 on 2024-12-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendancelisting', '0003_attendance_isapproved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='isApproved',
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_approved',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], default='pending', max_length=20, verbose_name='Approval Status'),
        ),
    ]
