# Generated by Django 5.1.3 on 2024-12-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_methods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmethod',
            name='test_description',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
