# Generated by Django 5.1.3 on 2024-12-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_methods', '0002_testmethod_test_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmethod',
            name='test_id',
        ),
        migrations.AddField(
            model_name='testmethod',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
