# Generated by Django 5.1.3 on 2024-12-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_methods', '0003_remove_testmethod_test_id_testmethod_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmethod',
            name='id',
        ),
        migrations.AddField(
            model_name='testmethod',
            name='test_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
